<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NoxTTS</AssemblyName>
    <RootNamespace>NoxTTS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
